[package]
name = 'FLOO'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies]
AptosFramework = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-framework'}
AptosToken = {git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-token'}

[addresses]
admin = "0x123"
escrow = "0x1234"